### ISSUE TITLE
dev-lang/julia won't compile against openblas -int64

### ISSUE THREAD

**Issue by gpoulin** [gentoo-science/sci#102]
On x86_64 julia tries to link against Blas using the 64bits integer interface which fail if the system Blas doesn't use 64bits integer interface.

By adding `int64` in `IUSE` and adding the following code in `src_prepare()` does the trick.

```bash
use int64 || sed -i -e "s|^USE_BLAS64.*|USE_BLAS64 = 0|g" Make.inc
```

However it's not really elegant. The best would be to detect the interface of the Blas library that we are linking against and apply the modification if needed. However I'm not skilled enough to write an ebuild that would do that.

**Comment by jlec** [comment]
Please reopen if still exist
