### ISSUE TITLE
tophat-2.0.9 needs explicit boost paths on Gentoo Prefix

### ISSUE THREAD

**Issue by mschubert** [gentoo-science/sci#216]
tophat-2.0.9 fails to build with standard settings on Gentoo Prefix because it autodetects boost from the host system.

The following flags are needed in `src_configure()` to make it work:

    autotools-utils_src_configure \
        --with-boost=$EPREFIX/usr \
        --with-boost-libdir=$EPREFIX/usr/lib

**Comment by mmokrejs** [comment]
Are you sure it is needed?


>>> Emerging (1 of 1) sci-biology/tophat-2.0.8::gentoo
 * tophat-2.0.8.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                                                                                                                                             [ ok ]
>>> Unpacking source...
>>> Unpacking tophat-2.0.8.tar.gz to /var/tmp/portage/sci-biology/tophat-2.0.8/work
>>> Source unpacked in /var/tmp/portage/sci-biology/tophat-2.0.8/work
>>> Preparing source in /var/tmp/portage/sci-biology/tophat-2.0.8/work/tophat-2.0.8 ...
 * Applying tophat-2.0.8-flags.patch ...                                                                                                                                                                                                                                                                                [ ok ]
 * Running eautoreconf in '/var/tmp/portage/sci-biology/tophat-2.0.8/work/tophat-2.0.8' ...
 * Running aclocal ...                                                                                                                                                                                                                                                                                                  [ ok ]
 * Running autoconf --force ...                                                                                                                                                                                                                                                                                         [ ok ]
 * Running autoheader ...                                                                                                                                                                                                                                                                                               [ ok ]
 * Running automake --add-missing --copy --force-missing ...                                                                                                                                                                                                                                                            [ ok ]
 * Running elibtoolize in: tophat-2.0.8/
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-biology/tophat-2.0.8/work/tophat-2.0.8 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/sci-biology/tophat-2.0.8/work/tophat-2.0.8_build"
 * econf: updating tophat-2.0.8/build-aux/config.guess with /usr/share/gnuconfig/config.guess
 * econf: updating tophat-2.0.8/build-aux/config.sub with /usr/share/gnuconfig/config.sub
/var/tmp/portage/sci-biology/tophat-2.0.8/work/tophat-2.0.8/configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --libdir=/usr/lib64 --docdir=/usr/share/doc/tophat-2.0.8 --disable-optim --disable-debug
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gawk... (cached) gawk
checking for x86_64-pc-linux-gnu-g++... x86_64-pc-linux-gnu-g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-pc-linux-gnu-g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of x86_64-pc-linux-gnu-g++... none
checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
checking whether we are using the GNU C compiler... yes
checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking whether x86_64-pc-linux-gnu-gcc understands -c and -o together... yes
checking dependency style of x86_64-pc-linux-gnu-gcc... none
checking whether make sets $(MAKE)... (cached) yes
checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
checking for a Python interpreter with version >= 2.4... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib64/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python2.7/site-packages
checking for boostlib >= 1.38.0... yes
checking for bamlib... yes
checking build system type... x86_64-pc-linux-gnu
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread-mt... yes
checking for exit in -lboost_system-mt... yes

**Comment by mschubert** [comment]
At the time when I reported the bug - yes, it was needed.

However, the boost autodetect may have changed since then and no longer suffer from that drawback.

**Comment by mschubert** [comment]
I'm closing this because the offending version is no longer in the science tree and all versions that are there do find boost.
