### ISSUE TITLE
NumPy can't find ATLAS libraries

### ISSUE THREAD

**Issue by chatcannon** [gentoo-science/sci#228]
See this issue at bugs.funtoo.org: http://bugs.funtoo.org/browse/FL-1224
I'm not entirely sure where the best place to report this problem is, given that ATLAS is only in the gentoo-science overlay but the NumPy ebuilds are in the main portage tree.

The NumPy ebuilds in both gentoo and funtoo strip out any information about ATLAS. This causes the NumPy build process to emit several warnings. Even if pkg-config blas actually points to ATLAS, NumPy doesn't know that it is ATLAS so any ATLAS-specific code (e.g. stuff that checks the ATLAS version to see whether various additional routines are present) is not run.

The numpy site.cfg mechanism can include information about much more than just BLAS and LAPACK - e.g. FFT libraries - and is used by lots of other python numerical packages. However, I'm not sure how much of its functionality is used. In principle the easiest long-term solution could be to have a numpy-distutils.eclass which generates a site.cfg file according to USE flags and can be included by every Python numerical package which uses site.cfg, but this might be overkill if all it is used for is to find which BLAS library to use.

**Comment by jlec** [comment]
As the funtoo bug says things are fine, I am closing this one.
