### ISSUE TITLE
VampirTrace-5.14.4

### ISSUE THREAD

**Issue by necrose99** [gentoo-science/sci#272]
mlieber/dcount/dcount.php?package=gputrace&get=VampirTrace-5.14.4-gpu2.tar.gz

http://tu-dresden.de/die_tu_dresden/zentrale_einrichtungen/zih/forschung/projekte/vampirtrace/accelerator/index_html/document_view?body_language=en?body_language=en

unfortunately  my repo clone it too far out of sync to try to pull req... 

anycase 

anyhow i'd just clone old ebuild see if it test bumpes... atm WEB for the tar.gz is down so repomanz.sh fails

**Comment by marbre** [comment]
Bumped it: https://github.com/gentoo-science/sci/commit/f3519496d76a50ae5c08f4e57fa01e0f651836f8
