### ISSUE TITLE
virtual/blas-2.1-r3 needs eigen version bump

### ISSUE THREAD

**Issue by stharward** [gentoo-science/sci#309]
virtual/blas-2.1-r3 can be satisfied by >=dev-cpp/eigen-3.1.2.  eigen-3.1.3 is stable in Gentoo's main portage, but this package doesn't actually provide any of the blas libs.  So a careless depclean can result in, say, the blas-reference package being uninstalled (because it's not necessary to satisfy the virtual dependency), even though it actually provides the necessary libraries.

virtual/blas-2.1-r3.ebuild needs to be tweaked to either depend on a version of eigen from the science overlay, or >=dev-cpp/eigen-3.1.4 (higher than main portage, but lowest of science overlay).

**Comment by jlec** [comment]
Could you please send a pull request and set the lowest version to 3.1.4?
