### ISSUE TITLE
emerge: there are no ebuilds to satisfy "app-text/ghostscript-gpl[cups]"

### ISSUE THREAD

**Issue by github4uw** [gentoo-science/sci#341]
Hi.
I am using gentoo_prefix on a Mac OS 10.10 with prefix=/gentoo.
I followed this installation guide https://github.com/cschwan/sage-on-gentoo
When I try to emerge -av sage I got a long list of required keyword-, mask- and use-changes. I may be added about 40 new keywords. After this I still get the following:
$ emerge -av sage
--- Invalid atom in /gentoo/etc/portage/package.accept_keywords/sage: dev-python/python-openid-2.2.5-r1

These are the packages that would be merged, in order:

Calculating dependencies... done!

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-lang/python:3.3

  (dev-lang/python-3.3.3:3.3/3.3::gentoo_prefix, installed) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (dev-lang/python-3.3.3:3.3/3.3::gentoo_prefix, ebuild scheduled for merge) pulled in by
    >=dev-lang/python-3.3.2-r2:3.3[sqlite] required by (dev-python/rpy-2.5.4:0/0::gentoo_prefix, ebuild scheduled for merge)
                                   ^^^^^^                                                                                                                       
    >=dev-lang/python-3.3.2-r2:3.3[readline,sqlite] required by (dev-python/ipython-2.3.0:0/0::gentoo_prefix, ebuild scheduled for merge)
                                            ^^^^^^                                                                                                                           
    >=dev-lang/python-3.3.2-r2:3.3[sqlite?] required by (dev-python/sqlalchemy-0.9.8:0/0::gentoo_prefix, ebuild scheduled for merge)
                                   ^^^^^^^                                                                                                                              

app-admin/eselect-opengl:0

  (app-admin/eselect-opengl-1.2.7:0/0::gentoo_prefix, installed) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (app-admin/eselect-opengl-1.3.1-r1:0/0::gentoo_prefix, ebuild scheduled for merge) pulled in by
    >=app-admin/eselect-opengl-1.3.0 required by (x11-proto/glproto-1.4.17-r1:0/0::gentoo_prefix, ebuild scheduled for merge)
    ^^                         ^^^^^                                                                                                                                                

sys-libs/zlib:0

  (sys-libs/zlib-1.2.8-r1:0/0::gentoo_prefix, installed) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (sys-libs/zlib-1.2.8-r1:0/0::gentoo_prefix, ebuild scheduled for merge) pulled in by
    >=sys-libs/zlib-1.2.5.1-r2:0[minizip] required by (dev-lang/R-3.1.2:0/0::gentoo_prefix, ebuild scheduled for merge)
                                 ^^^^^^^                                                                                                                   

It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.

emerge: there are no ebuilds to satisfy "app-text/ghostscript-gpl[cups]".
(dependency required by "net-print/cups-9999" [ebuild])
(dependency required by "dev-java/icedtea-bin-7.2.5.3[X]" [ebuild])
(dependency required by "virtual/jdk-1.7.0" [ebuild])
(dependency required by "virtual/jre-1.7.0" [ebuild])
(dependency required by "dev-java/java-config-2.1.11-r3" [ebuild])
(dependency required by "sci-chemistry/sage-jmol-bin-14.2.4::sage-on-gentoo[-x86-winnt]" [ebuild])
(dependency required by "sci-mathematics/sage-notebook-0.11.0-r100::sage-on-gentoo[java]" [ebuild])
(dependency required by "sci-mathematics/sage-6.4-r1::sage-on-gentoo" [ebuild])
(dependency required by "sci-mathematics/sage-data-conway_polynomials-0.4-r2::sage-on-gentoo" [ebuild])

Does someone have an idea how to get this to work?
Thanks!

**Comment by kiwifb** [comment]
While for a while I was trying to maintain a working sage-on-gentoo on mac it has fallen behind a bit. However I never really supported sage-notebook[java] so the first step in my recommendation would be to get 
```
sci-mathematics/sage-notebook -java
```
in etc/portage/package.use it would obviously get you further along. The main issue on the mac prefix side is to be stuck with gcc-apple-4.2.x sage and its components need a more recent compiler. I tried to require clang for some ebuilds on mac but really so long as we are stuck with that compiler things won't go smoothly. 

I will fix the atom problem though.

**Comment by kiwifb** [comment]
Hum for the invalid atom instead of making your own list just link package.keywords/sage from the overlay to some place under /gentoo/etc/portage/... the master file doesn't have any invalid atoms.

**Comment by kiwifb** [comment]
Say, why did you open the issue here rather than https://github.com/cschwan/sage-on-gentoo/issues ?
I am closing this here as being misplaced. You are welcome to submit further sage-on-gentoo issues at the above address.
