### ISSUE TITLE
dev-util/amdapp-2.8 probably won't work on x86

### ISSUE THREAD

**Issue by marbre** [gentoo-science/sci#357]
I just bumped the AMD APP SDK to v2.9. I noticed that in the 2.8 ebuild the temporary build directory is set to

>MY_P="AMD-APP-SDK-v2.8-RC-lnx64"
>S="${WORKDIR}/${MY_P}"

I am quite sure this will fail and hopefully solved this within the 2.9 ebuild. Should we fix this vor 2.8 or just drop that ebuild. It seems v2.8 isn't downloadable anymore, but only took a very quick look.

**Comment by jlec** [comment]
Feel free to drop old versions if there is no obvious reason to keep then. Especially if they don't build or are not downloadable.

**Comment by marbre** [comment]
Okay, I dopped v2.89 with commit 58e9888d4d5da475c4f27e04ab34ce42365b0533.

**Comment by marbre** [comment]
I was a little to fast... I fixed v2.8 and added a link to the download archive.
