### ISSUE TITLE
Genebank sequence packages

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#366]
Hi guys, I recently started getting a bit more hands-on with genetics, and I am using some genebank genome sequences (e.g. 
ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Mus_musculus/GRCm38.p3
).

I usually keep them under `~/genomes`, which is not bad. However, since these files are exclusively used for reference, and I don't (and almost all other users do not) actually edit them or contribute to upstream, it makes no sense for my user to have write permission to the directory. In fact, it makes no sense to even have them in my home directory in the first place, since they are not specific to me/my user and are used exclusively like you would some library (sourced in my data analysis scripts).

Do you think it would be sensible/feasible/worthwhile to make a meta package for genebank, with single packages for each genome, or just make one big package with single genomes controlled by use flags? If yes, what would be a good place to extract these files? `/opt/genebank` maybe?

**Comment by junghans** [comment]
See: http://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
If `genebank` is architecture independent data `/usr/share/genebank` would be the place.

Depending on how big the `genebank ` is, I would consider the following order. If it is small, just do one package. If it is big install only parts selected through use flags. If it is a lot of small files (long merge times) do multiple packages.

**Comment by TheChymera** [comment]
Apparently portage can't fetch directories? (heard that in IRC) can you confirm this?

**Comment by jlec** [comment]
No, only files.

**Comment by TheChymera** [comment]
@jlec any ideas how I can fetch the directory? I was thinking of recreating the directory structure via portage and getting the files per-name, but there are TOO many....

**Comment by jlec** [comment]
Can't you get a tarball? How is the license? Can we create our own tarball?

**Comment by TheChymera** [comment]
It's public domain ([see here](http://en.wikipedia.org/wiki/GenBank)), so I guess we can do pretty much whatever we like. BUT, it is quite huge. Where would we put it?

**Comment by jlec** [comment]
If you provide a script to me which downloads and packs those files, then I will download them and put them on my Dev space.

**Comment by mmokrejs** [comment]
I think it is not worth the effort. The volume is huge and infra# herd will not like you. If you think you want to write a tool/script to fetch the files then make it the package itself. But not placing all GenBank genomes into a package, that is not meaningful. Also, GenBank has them in different directories and their placement is important (different annotation). I fear you will mess it up and only confuse users, sorry to say that. ;) Sites IMHO have their own rsync-based scripts so I don't expect any large user-base either. :(

My own, local *partial* copy of GenBank genomes takes 1.4TB and I did not even fetch everything. Just to have it? No, thanks, no space.

There are plenty of other bugs in sci overlay which need your effort.

**Comment by jlec** [comment]
Thanks for this information, so we will never provide this by our package manager. Nevertheless we can provide the tools to fetch it.
