### ISSUE TITLE
multilib wrapping of fortran headers in openmpi considered harmful (in its current state)

### ISSUE THREAD

**Issue by kiwifb** [gentoo-science/sci#372]
So I synced stuff this morning and I got a new openmpi and a new nwchem to build with openmpi.
After upgrading openmpi to 1.8.4-r2 nwchem started and failed at configuration the config.log was full of stuff like
```
Warning: mpif-sentinels.h:12: Illegal preprocessor directive
...
mpif-config.h:1.1:
    Included at mpif.h:54:
    Included at conftest.f:2:

/* This file is auto-generated by multilib-build.eclass
 1
Error: Non-numeric character in statement label at (1)
```
The multibuild wrapping is nice but the current format is definitely C/C++ oriented, so when the mpif-config.h looks like this it chokes gfortran
```
/* This file is auto-generated by multilib-build.eclass
 * as a multilib-friendly wrapper. For the original content,
 * please see the files that are #included below.
 */

#if defined(__x86_64__) /* amd64 */
#	if defined(__ILP32__) /* x32 ABI */
#		error "abi_x86_x32 not supported by the package."
#	else /* 64-bit ABI */
#		include <x86_64-pc-linux-gnu/mpif-config.h>
#	endif
....
```
If there is an option so that gfortran will parse C/C++ style preprocessing instructions we should add it everywhere mpif90 is needed, and is gfortran, I don't know how other compilers digest this.

Even better would be to find a way to have fortran friendly wrappers so we wouldn't have to worry about support in a particular compiler.

**Comment by kiwifb** [comment]
Adding  -cpp won't solve the problem with gfortran as files included with the fortran include directive aren't going through cpp. I don't think we can support wrapping fortran header at this stage.

**Comment by junghans** [comment]
I see! For a similar reason I already moved the mod files of mpich{,2} to `/usr/$(get_libdir)` (beside the fact that OpenMPI installs them there anyhow).

Maybe we need to do something similar for the `mpif*.h`.

Alternatively, due to bug #540294 and bug #540392, we could not support 32-bit fortran on amd64 at all.

**Comment by kiwifb** [comment]
I have looked into it a little bit and preprocessing in fortran (and gfortran in particular) is hard. I would abandon 32bit fortran for now because I cannot think of a way of doing what is done in C/C++ in fortran. I'll have to look at those fine bugs later.

**Comment by junghans** [comment]
@mgorny: What would be the better way to preserve the fortran header in `/usr/include` using `mulitlib-build.eclass` without having to move them around manually?

**Comment by kiwifb** [comment]
In the meantime should we remove the stuff from openmpi and mpich as it is broken.

**Comment by junghans** [comment]
We could either mask abi_x86_32 or move the fortran header back in the right place after the install.

**Comment by kiwifb** [comment]
I don't like the idea of moving stuff back. That feels unnecessary. Not sure about the masking. I wonder in general about the viability of multilib fortran. The multilib-build eclass actually discourage using MULTILIB_WRAPPED_HEADERS:
```
Please note that header wrapping is *discouraged*. It is preferred to install all headers in a subdirectory of libdir and use pkg-config to locate the headers. Some C preprocessors will not work with wrapped headers.
```
Of course it a pain but unless we actually get the multilib eclass to point towards ABI specific include directories through CPPFLAGS (-I/path rather than -Dswitch) I don't think this is feasible.

**Comment by junghans** [comment]
Ok, I though about this again, because `mpicc` and friends are basically wrapper scripts installed the header into an place somewhere in `/usr/lib` should be ok as mpicc will inject the right `-I` flags. We basically just need to build the mpi package with `--program-prefix=${CHOST}-` and `--includedir=$(libdir)/XXX`. Maybe that could be a good time to combine this with @jsbronder's empi effort.

**Comment by kiwifb** [comment]
I think that's a very good idea. I cannot remember from the top of my head if we can do something similar for mpich but it suffers the same disease.

**Comment by junghans** [comment]
@jsbronder pointed out to me that it might be time to drop `mpich2`. Or we only need to convert `openmpi` and `mpich`.

One problem might be that cmake by default is not using `mpicc`, but simply tries to find libmpi.

**Comment by mgorny** [comment]
I'm sorry but my knowledge of Fortran was pretty much focused on 'I have seen it, I don't see any real use for it'. Why do the headers need to be wrapped anyway? Are they generated or something?

**Comment by kiwifb** [comment]
Yes they are generated, how they will vary between 32 and 64bit on a platform, I don't know.
I am not sure why I would want to support multilib with mpi but I guess it's an effort at complete support. The people that have the knowledge an use of fortran are saying that the wrapping won't work for fortran header because preprocessing in fortran is kind of primitive and doesn't extend to included files. The intel fortran compiler may be able to do it but it may be the only one.

**Comment by mgorny** [comment]
I'm honestly wondering if mpi is able to do multilib at all. I mean, if you wouldn't have to have any specific support on server.

**Comment by kiwifb** [comment]
The only requirement would be that the compute nodes are also multilib. In effect most install will have some or all their stuff on a shared file system.
Most of the clusters I have dealt with are built with commercial distro/OS and are effectively multilib out of the box. The stuff that the user want is rarely installed multilib and very seldom you are cornered into compiling  something in 32 bit while the default is 64.

But for the sake of the argument, commercial stuff like IBM POE (nowadays just PE, IBM own MPI implementation) is multilib.

**Comment by junghans** [comment]
We can always leave it like it is and not port mpi to 32 bit at all, but it seems useful for boost and fftw.

**Comment by mgorny** [comment]
I'd appreciate if someone could provide a diff between the headers generated by Fortran. Maybe we could devise a specific solution.

**Comment by kiwifb** [comment]
Looks like this is now completely fixed https://github.com/gentoo-science/sci/commit/bda9a630a01f197f387fa95cbbcc0f2c88f562d3
