### ISSUE TITLE
dev-util/amdapp-2.8 Version bump

### ISSUE THREAD

**Issue by jlec** [gentoo-science/sci#380]
(https://bugs.gentoo.org/show_bug.cgi?id=541836)
Perhaps a version bump is necessary. 

http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/#

Also what about adding a fetch restriction into the ebuild. I got this message when tried to emerge 2.8 version: 
Warning: No mirrors available for file 'AMD-APP-SDK-v2.8-lnx64.tgz'
[31;01m * [39;49;00mFetch failed for 'dev-util/amdapp-2.8', Log file:
[31;01m * [39;49;00m '/var/tmp/portage/dev-util/amdapp-2.8/temp/build.log'
 * Package:    dev-util/amdapp-2.8
 * Repository: science
 * Maintainer: gentryx@gmx.de cluster@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc examples kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
 * AMD doesn't provide direct download links. Please download
 *  from http://developer.amd.com/tools/heterogeneous-computing/amd-accelerated-parallel-processing-app-sdk

**Comment by marbre** [comment]
See https://github.com/gentoo-science/sci/pull/358
Am 02.03.2015 08:22 schrieb Justin <notifications@github.com>:(https://bugs.gentoo.org/show_bug.cgi?id=541836)
Perhaps a version bump is necessary. 

http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/#

Also what about adding a fetch restriction into the ebuild. I got this message when tried to emerge 2.8 version: 
Warning: No mirrors available for file 'AMD-APP-SDK-v2.8-lnx64.tgz'
[31;01m * [39;49;00mFetch failed for 'dev-util/amdapp-2.8', Log file:
[31;01m * [39;49;00m '/var/tmp/portage/dev-util/amdapp-2.8/temp/build.log'


Package:    dev-util/amdapp-2.8
Repository: science
Maintainer: gentryx@gmx.de cluster@gentoo.org

USE:        abi_x86_64 amd64 elibc_glibc examples kernel_linux userland_GNU
FEATURES:   preserve-libs sandbox userpriv usersandbox
AMD doesn't provide direct download links. Please download
 from http://developer.amd.com/tools/heterogeneous-computing/amd-accelerated-parallel-processing-app-sdk

**Comment by marbre** [comment]
Here my comment on https://bugs.gentoo.org/show_bug.cgi?id=541836


>Well, I already bumped to 2.9 on the first of February. Version 2.8 was dropped therefore.
Version 2.9.1 is currently proposed as pull request [1], as I don't find the time to test it. Any help, testing the new 2.9.1 ebuild is appreciated.


>[1] https://github.com/gentoo-science/sci/pull/358
