### ISSUE TITLE
sci-libs/dcmtk-3.6.0 (only version available) still fails to build

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#387]
Hello again. I waited a while, synced my overlay, and tried to build `sci-libs/dcmtk-3.6.0` again - it fails, with [this very long build log]( https://bpaste.net/show/248f8d2970d6). I hope it is ok if I do not try to paste that here.

**Comment by jlec** [comment]
Could you please provide /var/tmp/portage/sci-libs/dcmtk-3.6.0/temp/environment

**Comment by TheChymera** [comment]
I don't know what happened in the mean time, but now it works again :)
