### ISSUE TITLE
dev-util/f90-cache new version

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo-science/sci#418]
Can you bump the version from 0.94 to 0.95?
0.94 is no longer available.
Here is the source:
http://people.irisa.fr/Edouard.Canot/f90cache/f90cache-0.95.tar.bz2

**Comment by marbre** [comment]
Bumped with commit fd3a64680d8762571179527265cc4c0422c9492a. Feel free to bump by yourself next time and send a pull request.
