### ISSUE TITLE
dev-libs/utf8proc-1.2 only installs symlink

### ISSUE THREAD

**Issue by cookiemon** [gentoo-science/sci#427]
After emerging dev-libs/utf8proc-1.2 I have the following situation:
```
# ls -lah /usr/lib/libutf8proc*    
lrwxrwxrwx 1 root root   20 May 24 13:16 /usr/lib/libutf8proc.so -> libutf8proc.so.1.2.0
#
```
So it is missing the library itself and only installed a symlink to nothing.

**Comment by jlec** [comment]
+*utf8proc-1.2-r1 (25 May 2015)
+
+  25 May 2015; Justin Lecher <jlec@gentoo.org> +utf8proc-1.2-r1.ebuild,
+  -utf8proc-1.2.ebuild, files/utf8proc-1.2-buildflags.patch, metadata.xml:
+  dev-libs/utf8proc: Fix build process, https://github.com/gentoo-
+  science/sci/issues/427
+

Fix in 1e770e85618b77f807c9be867daee3fd47c9980d
