### ISSUE TITLE
sci-libs/gsl, sci-libs/{cblas,lapack,blas}-reference fails to install with ABI_X86="64 32"

### ISSUE THREAD

**Issue by madjestic** [gentoo-science/sci#438]
Hey folks,

After multilib update, according to the eselect news item:
> 2015-03-28-true-multilib
>  Title                     True multilib support on amd64
>  Author                    Michał Górny <mgorny@gentoo.org>
...
>> relevant parts: set \*/\* abi_x86_32 in package.use
>> emerge -C 'app-emulation/emul-linux-x86*'
>>, followed by a @world upgrade
...

, I attempted to 'emerge -av --newuse sci-libs/gsl' and get this: [http://lpaste.net/134587](http://lpaste.net/134587)
...
ERROR: sci-libs/gsl-1.16-r2::science failed (install phase):
...

**Comment by jlec** [comment]
ABI_X86="64 32" emerge gsl

I am nearly finished with fixing it. The alternatives stuff need to be run only in the .._all phase not in every ABI phase.

**Comment by jlec** [comment]
Partially fixed in 83bbe850f91ca9ffd05dc7dd6a0051ecb50b1fd2

**Comment by madjestic** [comment]
It seems that the fix has partially worked, not I am getting this though: http://lpaste.net/134767
( similar as above, but sci-libs/blas-reference)

**Comment by TheChymera** [comment]
@jlec why `ABI_X86="64 32" emerge gsl` and not `ABI_X86="64 32" emerge -1 gsl` ? should't gsl be pulled in as a dep of cblas?

**Comment by jlec** [comment]
as you like, but the ebuild as a result of recent eselect changes is broken.

**Comment by TheChymera** [comment]
@kiwifb directed me here in reply to my ongoing issues detailed in the above linked issue.

In brief, I keep getting `!!! Error: Action update unknown` when I try to emerge c/blas-reference or lapack-reference. Could it be related to this issue?

**Comment by madjestic** [comment]
I read about your issue, methinks we need to wait till somebody fixes the ebuild.

**Comment by TheChymera** [comment]
Are you sure we have the same issue? I kind of need this yeasterday :-/

**Comment by fusion809** [comment]
My issue was closed as a duplicate of this one and it would be nice if someone could actually solve this one.
