### ISSUE TITLE
PythonTeX: why dependency on xetex and matplotlib?

### ISSUE THREAD

**Issue by equaeghe** [gentoo-science/sci#441]
In the PythonTeX ebuild, there is an RDEPEND on xetex and matplotlib that is unclear to me. Are they really run-time *requirements*?

**Comment by TheChymera** [comment]
PythonTeX is used to create python plots on the fly and insert them directly in LaTeX documents at build time. So you will almost certainly need matplotlib to be able to do anything with it.

I am unsure whether either matplotlib or xetex are used by pythontex internally, though. @gpoore do you?

**Comment by equaeghe** [comment]
Generating plots using Python is just one of many possible applications. I use it for autogenerating documents from data files and have actually never used it for generating plots. Pulling in matplotlib should, if anything, be behind a use flag. But, IMHO, I think even this is a misuse of the dependency system unless something extra needs to be installed on the PythonTeX side.

**Comment by TheChymera** [comment]
What about xetex?

**Comment by equaeghe** [comment]
I have no idea why xetex could be listed as a run-time dependency.

**Comment by gpoore** [comment]
For general use, neither matplotlib nor xetex should be required. On the Python side, you need 2.7+ or 3.2+.  On the LaTeX side, you would want some LaTeX engine, but xetex, pdftex, or luatex would be fine. There is no code in PythonTeX itself that depends on the presence of xetex or matplotlib.

**Comment by TheChymera** [comment]
ok, @equaeghe , so for us that means we cross matplotlib off ... aaand, what options do we have to make sure any latex engine at all is available?

**Comment by equaeghe** [comment]
Well:

```
# equery b /usr/bin/pdftex
 * Searching for /usr/bin/pdftex ... 
app-text/texlive-core-2014-r4 (/usr/bin/pdftex -> pdftex-texlive-core-2014)
app-text/texlive-core-2014-r4 (/usr/bin/pdftex-texlive-core-2014)
# equery b /usr/bin/luatex
 * Searching for /usr/bin/luatex ... 
app-text/texlive-core-2014-r4 (/usr/bin/luatex)
# equery b /usr/bin/xetex
 * Searching for /usr/bin/xetex ... 
app-text/texlive-core-2014-r4 (/usr/bin/xetex)
```

and here xetex is installed only because of the xetex use flag being active as required by the current version of the pthontex ebuild.

So: plain texlive-core.

If you really want to ensure some LaTeX engine (reasonable unless pythontex can be used in some none-LaTeX macro package): 

```
# equery b /usr/bin/latex
 * Searching for /usr/bin/latex ... 
app-text/texlive-core-2014-r4 (/usr/bin/pdftex-texlive-core-2014)
dev-texlive/texlive-latex-2014 (/usr/bin/latex -> pdftex)
# equery b /usr/bin/xelatex
 * Searching for /usr/bin/xelatex ... 
app-text/texlive-core-2014-r4 (/usr/bin/xetex)
dev-texlive/texlive-xetex-2012 (/usr/bin/xelatex -> xetex)
# equery b /usr/bin/pdflatex
 * Searching for /usr/bin/pdflatex ... 
app-text/texlive-core-2014-r4 (/usr/bin/pdftex-texlive-core-2014)
dev-texlive/texlive-latex-2014 (/usr/bin/pdflatex -> pdftex)
# equery b /usr/bin/lualatex
 * Searching for /usr/bin/lualatex ... 
app-text/texlive-core-2014-r4 (/usr/bin/luatex)
dev-texlive/texlive-latex-2014 (/usr/bin/lualatex -> luatex)
```

Then dev-texlive/texlive-latex seems the best option. People that use xetex will install it anway.

**Comment by TheChymera** [comment]
ok, I am looking at the ebuild now. I think I had put the matplotlib dep inside to indicate that pythontex would not work properly with matplotlib pre-1.2. But since those days are long past, I guess it is time to remove it anyway.

Just out of curiosity, how would one best deal with such a scenario? (very optional dep, but version restricted) - I can't just neglect that info entirely.

**Comment by equaeghe** [comment]
Your last question is one for a Gentoo dev communication channel... Of course you could put it behind a use flag.

**Comment by gpoore** [comment]
matplotlib before 1.2 should work. The big thing about 1.2+, which I mention once or twice in the PythonTeX docs, is that it added more backends, so it has much better potential for TeX integration.

**Comment by TheChymera** [comment]
@equaeghe I think you can close this now?
