### ISSUE TITLE
sci-libs/openblas-0.2.14 doesn't appear in eselect

### ISSUE THREAD

**Issue by uvok** [gentoo-science/sci#455]
When I emerge openblas, the following appears in the elog:

    >>> Messages generated by process 23254 on 2015-07-22 20:20:23 CEST for package sci-libs/openblas-0.2.14:
    ERROR: prerm
    eselect blas update  returned 
    eselect cblas update  returned 

When i run eselect, I get

    $ eselect blas list
    $ eselect cblas list

openblas itself emerged correctly.

Is this maybe related to #447?

edit: emerge --info

    Portage 2.2.20 (python 2.7.9-final-0, default/linux/amd64/13.0/desktop, gcc-4.8.4, glibc-2.20-r2, 4.0.5-gentoo x86_64)
    =================================================================
    System uname: Linux-4.0.5-gentoo-x86_64-Intel-R-_Core-TM-_i5-4590_CPU_@_3.30GHz-with-gentoo-2.2
    KiB Mem:     8049008 total,   2977708 free
    KiB Swap:          0 total,         0 free
    Timestamp of repository gentoo: Wed, 22 Jul 2015 16:00:01 +0000
    sh bash 4.3_p39
    ld GNU ld (Gentoo 2.25 p1.2) 2.25
    app-shells/bash:          4.3_p39::gentoo
    dev-java/java-config:     2.2.0::gentoo
    dev-lang/perl:            5.20.2::gentoo
    dev-lang/python:          2.7.9-r1::gentoo, 3.3.5-r1::gentoo, 3.4.1::gentoo
    dev-util/cmake:           3.2.2::gentoo
    dev-util/pkgconfig:       0.28-r2::gentoo
    sys-apps/baselayout:      2.2::gentoo
    sys-apps/openrc:          0.17::gentoo
    sys-apps/sandbox:         2.6-r1::gentoo
    sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
    sys-devel/automake:       1.4_p6-r2::gentoo, 1.11.6-r1::gentoo, 1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
    sys-devel/binutils:       2.25-r1::gentoo
    sys-devel/gcc:            4.8.4::gentoo
    sys-devel/gcc-config:     1.8::gentoo
    sys-devel/libtool:        2.4.6::gentoo
    sys-devel/make:           4.1-r1::gentoo
    sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
    sys-libs/glibc:           2.20-r2::gentoo
    Repositories:
    
    gentoo
        location: /usr/portage
        sync-type: rsync
        sync-uri: rsync://rsync.gentoo.org/gentoo-portage
        priority: -1000
    
    local
        location: /usr/local/portage
        masters: gentoo
        priority: 0
    
    dotnet
        location: /var/lib/layman/dotnet
        sync-type: laymansync
        sync-uri: git://anongit.gentoo.org/proj/dotnet.git
        masters: gentoo
        priority: 50
    
    haskell
        location: /var/lib/layman/haskell
        sync-type: laymansync
        sync-uri: git://github.com/gentoo-haskell/gentoo-haskell.git
        masters: gentoo
        priority: 50
    
    kaa
        location: /var/lib/layman/kaa
        sync-type: laymansync
        sync-uri: http://www.kaa.org.ua/gentoo
        masters: gentoo
        priority: 50
    
    maksbotan
        location: /var/lib/layman/maksbotan
        sync-type: laymansync
        sync-uri: git://anongit.gentoo.org/dev/maksbotan.git
        masters: gentoo
        priority: 50
    
    mpd
        location: /var/lib/layman/mpd
        sync-type: laymansync
        sync-uri: git://git.musicpd.org/master/mpd-gentoo-overlay.git
        masters: gentoo
        priority: 50
    
    qt
        location: /var/lib/layman/qt
        sync-type: laymansync
        sync-uri: git://anongit.gentoo.org/proj/qt.git
        masters: gentoo
        priority: 50
    
    science
        location: /var/lib/layman/science
        sync-type: laymansync
        sync-uri: git://anongit.gentoo.org/proj/sci.git
        masters: gentoo
        priority: 50
    
    sekyfsr
        location: /var/lib/layman/sekyfsr
        sync-type: laymansync
        sync-uri: git://github.com/npinto/sekyfsr-gentoo-overlay.git
        masters: gentoo
        priority: 50
    
    spike
        location: /var/lib/layman/spike
        sync-type: laymansync
        sync-uri: https://github.com/Spike-Pentesting/spike-overlay.git
        masters: gentoo
        priority: 50
    
    steam-overlay
        location: /var/lib/layman/steam-overlay
        sync-type: laymansync
        sync-uri: git://github.com/anyc/steam-overlay.git
        masters: gentoo
        priority: 50
    
    tox-overlay
        location: /var/lib/layman/tox-overlay
        sync-type: laymansync
        sync-uri: git://github.com/urras/gentoo-overlay-tox.git
        masters: gentoo
        priority: 50
    
    voyageur
        location: /var/lib/layman/voyageur
        sync-type: laymansync
        sync-uri: https://cafarelli.fr/git/voyageur-overlay/
        masters: gentoo
        priority: 50
    
    zugaina
        location: /var/lib/layman/zugaina
        sync-type: laymansync
        sync-uri: rsync://gentoo.zugaina.org/zugaina-portage
        masters: gentoo
        priority: 50
    
    ACCEPT_KEYWORDS="amd64"
    ACCEPT_LICENSE="* -@EULA"
    CBUILD="x86_64-pc-linux-gnu"
    CFLAGS="-O2 -pipe -march=native"
    CHOST="x86_64-pc-linux-gnu"
    CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt"
    CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
    CXXFLAGS="-O2 -pipe -march=native"
    DISTDIR="/usr/portage/distfiles"
    FCFLAGS="-O2 -pipe"
    FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
    FFLAGS="-O2 -pipe"
    GENTOO_MIRRORS="ftp://mirror.netcologne.de/gentoo/ http://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/ ftp://ftp.halifax.rwth-aachen.de/gentoo/ ftp://ftp.uni-erlangen.de/pub/mirrors/gentoo"
    LANG="en_US.utf8"
    LDFLAGS="-Wl,-O1 -Wl,--as-needed"
    MAKEOPTS="-j5"
    PKGDIR="/usr/portage/packages"
    PORTAGE_CONFIGROOT="/"
    PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
    PORTAGE_TMPDIR="/var/tmp"
    USE="X a52 aac aacs acl acpi aes alsa amd64 avx avx2 bash-completion berkdb bluetooth bluray branding bzip2 cairo cdda cdr cli consolekit cracklib crypt cups cxx dbus dri dts dvd dvdr emboss encode exif fam firefox flac fma3 fortran gdbm gif glamor gpg gpm gtk iconv ipv6 jpeg lame lcms libnotify mad mmx mmxext mng modules mp3 mp4 mpeg multilib ncurses nls nptl ogg opengl openmp pam pango pcre pdf png policykit popcnt ppds pulseaudio qt3support qt4 readline sdl session spell sqlite sse sse2 sse3 sse4_1 sse4_2 ssl ssse3 startup-notification svg tcpd threads tiff truetype udev udisks unicode upower usb vaapi vorbis vpx wxwidgets x264 xcb xml xv xvid zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="de en" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_3" RUBY_TARGETS="ruby19 ruby20" USERLAND="GNU" VIDEO_CARDS="fbdev intel vesa" XFCE_PLUGINS="clock trash" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
    Unset:  CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

**Comment by kiwifb** [comment]
And #438. Are you in a prefix or pure Gentoo?

**Comment by uvok** [comment]
I'm in a pure Gentoo.

**Comment by uvok** [comment]
Possibly the solution: I still has app-eselect/eselect-blas and app-eselect/eselect-cblas installed from the default gentoo repository.  I already wondered why blas and cblas appeared under Alternatives modules AND extra modules when typing eselect.
When emerging openblas again, I still got

     * Creating Alternative for blas
    !!! Error: Missing required parameter 'provider'
    exiting
     * Creating Alternative for cblas
    !!! Error: Missing required parameter 'provider'
    exiting
    >>> sci-libs/openblas-0.2.14 merged.

Openblas now appears in eselect:
    $ eselect  blas list
    Available providers for blas:
      [1]   openblas-openmp
     $ eselect  cblas list
    Available providers for cblas:
      [1]   openblas-openmp

But if I select it, I get a broken symlink

    lrwxrwxrwx 1 root root 24 Jul 19 10:36 /usr/lib64/libblas.a -> blas/reference/libblas.a
    lrwxrwxrwx 1 root root 25 Jul 19 10:36 /usr/lib64/libblas.so -> blas/reference/libblas.so

**Comment by marbre** [comment]
Did you check https://wiki.gentoo.org/wiki/User_talk:Houseofsuns?

**Comment by uvok** [comment]
No, haven't checked this yet, will do so now

**Comment by uvok** [comment]
Setup works fine now. Problem was indeed the old -eselect packages from main tree.
