### ISSUE TITLE
sci-libs/array-fire: LAPACKE_LIB not set, build_boost_compute.cmake not found

### ISSUE THREAD

**Issue by Giels** [gentoo-science/sci#463]
As the title says. These problems affect the 9999 version as of August 21 2015 when USE="opencl" is selected. -DLAPACKE_LIB=/usr/lib/lapack/reference/liblapack.so works on a manual source install. Some of the patches seem to be incorrect or out-of-date since the error about build_boost_compute.cmake does not appear with a source install.

Exact error messages:
-- Boost version: 1.56.0
CMake Error at src/backend/opencl/CMakeLists.txt:63 (INCLUDE):
  include could not find load file:

    /var/tmp/portage/sci-libs/arrayfire-9999/work/arrayfire-9999/CMakeModules/build_boost_compute.cmake

And

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LAPACKE_LIB
    linked by target "afcpu" in directory /var/tmp/portage/sci-libs/arrayfire-9999/work/arrayfire-9999/src/backend/cpu
    linked by target "afopencl" in directory /var/tmp/portage/sci-libs/arrayfire-9999/work/arrayfire-9999/src/backend/opencl

**Comment by marbre** [comment]
Thanks for reporting this @Giels. I fixed the boost-compute issue with https://github.com/gentoo-science/sci/commit/5f768d17470ad79d20b0d7c7e60d8cbbe21a7448.

The issue with lapack still remains anyway. I tried to get this fixed, when starting an ebuild for the arrayfire 3.0 stable release. Unfortunately I was not able adjust the [FindLAPACKE.cmake](https://github.com/arrayfire/arrayfire/blob/v3.0.2/CMakeModules/FindLAPACKE.cmake) module in a way that LAPACK**E** is found and that the LAPACK variables in dependence are set correctly. That is actually the main reason, why there is only 3.0_beta in the overlay.
Thus, any support is really appreciated, because I am currently lacking time to fix this.

**Comment by Giels** [comment]
I spoke too soon; the library seems to be actually /usr/lib/libreflapacke.so and even then, the current versions of atlas and lapacke might be missing symbols or arrayfire might not be linking correctly:

/usr/lib64/libreflapacke.so: undefined reference to `zlapmr_'
/usr/lib64/libreflapacke.so: undefined reference to `dpstrf_'
/usr/lib64/libatlas.so.3: undefined reference to `ATL_SetAtomicCount'
/usr/lib64/libreflapacke.so: undefined reference to `ctfttr_'
/usr/lib64/libreflapacke.so: undefined reference to `dsyconv_'
/usr/lib64/libreflapacke.so: undefined reference to `stpqrt2_'
/usr/lib64/libreflapacke.so: undefined reference to `zsyswapr_'
/usr/lib64/libreflapacke.so: undefined reference to `dtprfb_'
(and a ton more).

This is no longer for afopencl (this target now works with -DLAPACKE_LIB=/usr/lib/libreflapacke.so) but for image_processing/adaptive_thresholding_cpu and examples during linking.

I can successfully compile with -DBUILD_CPU=0 -DBUILD_EXAMPLES=0. While suboptimal, it works with these settings. Hopefully this will help.

**Comment by Giels** [comment]
Digging some more, using lapacke from svn with -DBUILD_DEPRECATED=1 -DLAPACKE=1 -DBUILD_SHARED_LIBS=1 -DBUILD_TESTING=0 seems to be necessary to get all the required symbols. I also opened an issue against the sci-libs/lapacke-reference ebuild because it does not compile correctly. Also, not renaming the library during install (which coincidentally seems to be the step which breaks the 9999 lapacke-reference install) allows correct autodetection of the lapacke library.

**Comment by marbre** [comment]
To keep this up-to-date:
I finally finished a modified `FindLAPACKE.cmake` which finds LAPACKE (which indeed is libreflapacke.so) via pkgconfig and also correctly determines against which LAPACK implementation the lib is linked. Just tested LAPACKE build against ATLAS, will test on another system on which uses lapack-reference. After cleaning the patch, this finally fixed -DBUILD_CPU (which also requires LAPACKE) and also brings as nearer to finally fix -BUILD_OPENCL.

**Comment by marbre** [comment]
Hopefully fixed now. Please reopen this issue or create new ones if any problems occur.

**Comment by eyalroz** [comment]
@marbre : I'm seeing this issue on Debian Stretch, with arrayfire version 3.3.1 which I just downloaded.

**Comment by marbre** [comment]
@eyalroz I haven't yet bumped to 3.3.1 due to a lack of time. Don't know if the FindLAPACKE.cmake was modified by upstream, originally my changes were merged.

**Comment by marbre** [comment]
@eyalroz I think you experienced issue https://github.com/arrayfire/arrayfire/issues/1419. This is already fixed in the latest arrayfire version available via the science overlay.
