### ISSUE TITLE
dev-python/notebook-4.0.4: Installation of MathJax symlink blocked

### ISSUE THREAD

**Issue by marbre** [gentoo-science/sci#478]
~~~
>>> Recording dev-python/notebook in "world" favorites file...

 * Messages for package dev-python/notebook-4.0.4:

 * 
 * Installation of a symlink is blocked by a directory:
 *   '/usr/lib64/python3.3/site-packages/notebook/static/components/MathJax'
 * This symlink will be merged with a different name:
 *   '/usr/lib64/python3.3/site-packages/notebook/static/components/MathJax.backup.0001'
 * 
 * 
 * Installation of a symlink is blocked by a directory:
 *   '/usr/lib64/python3.4/site-packages/notebook/static/components/MathJax'
 * This symlink will be merged with a different name:
 *   '/usr/lib64/python3.4/site-packages/notebook/static/components/MathJax.backup.0001'
 * 
 * 
 * Installation of a symlink is blocked by a directory:
 *   '/usr/lib64/python2.7/site-packages/notebook/static/components/MathJax'
 * This symlink will be merged with a different name:
 *   '/usr/lib64/python2.7/site-packages/notebook/static/components/MathJax.backup.0001'
 * 
>>> Auto-cleaning packages...
~~~

Before merging, I ran `ebuild notebook-4.0.4.ebuild install`, which was unfortunately not enough.. @flacjacket Could you take a look?

**Comment by marbre** [comment]
Unmerging and removing `rm -r /usr/lib64/python*/site-packages/notebook` solves the problem. It seems like the previously created MathJax directory cannot be replaced by a symlink. Therefore "upgrading" fails.

**Comment by flacjacket** [comment]
Right, the MathJax directory is left over from the previous notebook install and should be removed, I don't know if there is a way we can clobber that directory with the symlink to the system mathjax.

**Comment by marbre** [comment]
I discussed this with @jlec in IRC, seems to be a portage issue. Thus, hopefully not too many users had installed the notebook ebuild prior to the merge...

**Comment by kiwifb** [comment]
The original `ipython` ebuild had something to deal with that (for some reason it has been removed) but I have adopted the strategy in for `sage-notebook` which also uses `mathjax`:
```
pkg_preinst() {
	# remove old mathjax folder if present
	[[ -d "${ROOT}$(python_get_sitedir)/sagenb/data/mathjax" ]] \
		&& rm -rf "${ROOT}$(python_get_sitedir)/sagenb/data/mathjax"
}
```
Replace with the appropriate directories. Note that it is prefix ready as it is because `python_get_sitedir` includes the prefix path.

**Comment by jlec** [comment]
That's a way to go.

**Comment by marbre** [comment]
@kiwifb Thanks for the hint. I'll add this later today.

**Comment by kiwifb** [comment]
What I don't understand is why it has been removed from the `ipython` ebuilds in the main tree.
