### ISSUE TITLE
`sci-chemistry/openbabel` wxwidgets USE flag meaning for end user

### ISSUE THREAD

**Issue by fusion809** [gentoo-science/sci#495]
Hi, 

I thought that the wxwidgets USE flag for the `sci-chemistry/openbabel` package would mean a GUI for OpenBabel would be built using the wxwidgets toolkit. But I can't seem to find a GUI for openbabel on my system, even though I installed openbabel with wxwidgets USE flags enabled. 

Thanks for your time,
Brenton

**Comment by jlec** [comment]
Could you please show us a build.log?

**Comment by jlec** [comment]
Works here. Do you have ```obgui```installed?

**Comment by fusion809** [comment]
Ever so sorry, turns out this was an issue with Entropy, I thought I had installed OpenBabel with Portage, but I used Entropy. So I'm closing this issue and apologizing for wasting your time.
