### ISSUE TITLE
sci-biology/artemis-bin depends on non-existent ebuild sci-biology/bamview + manifest error

### ISSUE THREAD

**Issue by ahmedtd** [gentoo-science/sci#50]
There is a sci-biology/bamtools package.  I modified the ebuild in my tree to use this instead, but then run into a (separate, I believe) manifest error for the compiled artemis file downloaded from the sanger ftp.

The reason for the manifest error is that the expected size is 224 bytes larger than the downloaded file.

Regenerating the manifest (with ebuild artemis-bin-13.2.12.ebuild) changes the hashes in the Manifest file, but not the expected size.

**Comment by mschubert** [comment]
I just tried this and it works fine for the 16.0.11 that is in the sci tree. - Looks like this issue no longer applies.

**Comment by jlec** [comment]
> Looks like this issue no longer applies.

So let's close it. Please reopen if still exists.
