### ISSUE TITLE
eclass for MRIcron package

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#517]
I would like to write a package for [MRIcrom](http://www.mccauslandcenter.sc.edu/mricro/mricron/). Debian does it like so: http://anonscm.debian.org/cgit/debian-med/mricron.git/tree/debian/rules

I suspect it's the lazbuild lines that do the heavy lifting - is there any eclass that might help me deal with this package? I found no lazbuild eclass [here](https://devmanual.gentoo.org/eclass-reference/).

**Comment by dxli** [comment]
@TheChymera 

lazbuild is provided by dev-lang/lazarus
