### ISSUE TITLE
sci-libs/blas-reference-20131116-r1: install phase fails due to existance of the directory

### ISSUE THREAD

**Issue by suhr** [gentoo-science/sci#522]
Build log:

```
-- Install configuration: "Gentoo"
-- Installing: /var/tmp/portage/sci-libs/blas-reference-20131116-r1/image/usr/lib64/pkgconfig/refblas.pc
-- Installing: /var/tmp/portage/sci-libs/blas-reference-20131116-r1/image/usr/lib64/librefblas.so
make: Leaving directory '/var/tmp/portage/sci-libs/blas-reference-20131116-r1/work/lapack-3.5.0-amd64/BLAS'
!!! Error: /var/tmp/portage/sci-libs/blas-reference-20131116-r1/image//etc/env.d/alternatives/blas/reference already present. You need ot remove it before adding it again
Call stack:
    * alternatives_do_add (alternatives-common.bash:292)
    * do_add (alternatives.eselect:147)
    * check_do (core.bash:24)
    * do_action (core.bash:105)
    * main (eselect:309)
exiting
```

Btw, sci-libs/blas-reference-20131116 compiles fine.

**Comment by jlec** [comment]
know failure, see https://github.com/gentoo-science/sci/issues I am working on it and have a solution nearly ready.

**Comment by Haifen** [comment]
Bug also applies to sci-libs/blas-reference-99999999

**Comment by jlec** [comment]
Don't install for ```ABI_X86="32"```

**Comment by Haifen** [comment]
Kicked off compile with ABI_X86="64", which succeeded.  Thanks.  Will it be possible to do a 32-bit build at some point?

**Comment by jlec** [comment]
> Will it be possible to do a 32-bit build at some point?

Nearly finished. There were some huge problems, which are solved, but I need to update all ebuilds and clean the new eclasses.

**Comment by sylvchev** [comment]
Thank you for pointing this "-abi_x86_32" temporary solution, I took some time to figure it out.
