### ISSUE TITLE
fsl sources mirror

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#526]
FSL was recently bumped to `5.0.9`. One consequence thereof is that the `fsl-5.0.8` sources are no longer available from the FMRIB website.

Sadly, I have deleted my distfiles and no longer have the old sources. could any one of you who maybe still has the old sources mirror them? @kiwifb @jlec

**Comment by jlec** [comment]
Sorry, no. Try to drop a mail to the gentoo-science mailing list. Perhaps a user has them

**Comment by kiwifb** [comment]
Have to check but I probably have them.

**Comment by TheChymera** [comment]
@jlec @kiwifb apparentlz the 5.0.8 sources (though none of the earlier) can be downloaded via the internet archive. But I guess that is no proper mirror. Could you upload them to somewhere that is?

**Comment by kiwifb** [comment]
I have tarballs for 5.0.0, 5.0.4, 5.0.6 and 5.0.8. I can host one on a short term basis on the lmona.de server but it shouldn't be a long term solution either.

**Comment by TheChymera** [comment]
@kiwifb I would hazard a guess and say that save for you and me nobody needs fsl on gentoo (yet!). I already got the sources, so there is no need to trouble yourself with a temporary solution. I guess it would be better to look for a permanent one. @jlec can we archive some 1.3GB of sources somewhere on the official gentoo webspace?

**Comment by jlec** [comment]
Do we need to host all sources? isn't the latest version sufficient?

**Comment by kiwifb** [comment]
I don't think you have the right idea
```
frb15@p2n14-c /usr/local/pkg/fsl/SITE :ll -h
total 5.1G
drwxrwxr-x  2 ajd41 z001  32K May  5  2015 .
drwxrwxr-x 11 ajd41 z001  32K May  5  2015 ..
-rw-r--r--  1 ajd41 z001 1.3G Sep 20  2012 fsl-5.0.0-sources.tar.gz
-rw-r--r--  1 frb15 z001 1.3G May 10  2013 fsl-5.0.4-sources.tar.gz
-rw-r--r--  1 frb15 z001 1.4G May 19  2014 fsl-5.0.6-sources.tar.gz
-rw-r-----  1 frb15 z001 1.4G May  5  2015 fsl-5.0.8-sources.tar.gz
```
1.3GB is for one version of `fsl`. it includes a number of reference brain scans.

**Comment by jlec** [comment]
I could put the latest on my dev space.

**Comment by TheChymera** [comment]
For the time being the traffic should be negligible. Also, in a slightly related matter: Do we have any way to get some statistics on how many people are using which of our ebuilds?

**Comment by jlec** [comment]
sadly no. There was a GSOC project but that is trashed.

**Comment by TheChymera** [comment]
@jlec :( anyway, could you give me the download link so that I can update the ebuild? If you don't have more space, I guess we could just keep the newest version except the one being hosted upstream in your dev space. 

Do you think it would be appropriate to hard mask the newest version (hosted by upstream) - since it might get pulled down and replaced with a newer one at any time.

**Comment by jlec** [comment]
I need the tarball first so that I can upload it.

**Comment by TheChymera** [comment]
What about the link from the internet archive?

http://web.archive.org/web/http://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-5.0.8-sources.tar.gz

**Comment by jlec** [comment]
https://dev.gentoo.org/~jlec/distfiles/fsl-5.0.8-sources.tar.gz
