### ISSUE TITLE
python-future package

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#530]
It seems I will need [this package](https://pypi.python.org/pypi/future) as a nipype dependency in the near future. See upstream discussion:

https://github.com/nipy/nipype/issues/1271#issuecomment-155260437

any idea if it is already in gentoo? I tried these packages:

```
* dev-python/futures
     Available versions:  2.2.0 (~)3.0.2 (~)3.0.3 {doc PYTHON_TARGETS="pypy python2_7"}
     Homepage:            https://code.google.com/p/pythonfutures https://pypi.python.org/pypi/futures
     Description:         Backport of the concurrent.futures package from Python 3.2

* virtual/python-futures
     Available versions:  0 {PYTHON_TARGETS="pypy python2_7 python3_3 python3_4"}
     Description:         A virtual for the Python concurrent.futures module
```

But none of them lets me `from future import *` - whic is apparently what the nipype setup.py wants to see.

**Comment by kiwifb** [comment]
Doesn't look like it. I think they mean `http://python-future.org/`

**Comment by jlec** [comment]
no it isn't. the dev-python/futures packages are backports. future is a glue layer like six.

**Comment by TheChymera** [comment]
So I should package that if I want newer nipype versions to work, right?

**Comment by jlec** [comment]
better that
