### ISSUE TITLE
FSL not running out of the box

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#534]
I noticed after a fresh install of `fsl-5.0.8` that it requires some end-user help to actually work:

```
chymera@quiethost ~/FSL_GLM_work/GLM/_measurement_id_20151102_131136_4004_1_2 $ fslhd FLIRT_implement/corr_9_masked_flirt.nii.gz 
ERROR:: Environment variable FSLOUTPUTTYPE is not set!
Please make sure that the appropriate configuration file is sourced by your shell (e.g. by putting it in .profile).
e.g. bash or sh users add the line ". /etc/fslconf/fsl.sh"
e.g. tcsh or csh users add the line "source /etc/fslconf/fsl.csh"
chymera@quiethost ~/FSL_GLM_work/GLM/_measurement_id_20151102_131136_4004_1_2 $ fsl
You need to set the FSLDIR environment variable to point to the FSL installation directory before you can run anything.
```

Any idea how we can solve this directly from the ebuild?

@kiwifb

**Comment by kiwifb** [comment]
Can you check that `/etc/env.d/99fsl` has been installed properly? If so the environment may need to be "refreshed" with `env-update` and `source /etc/profile`. The latter shouldn't be necessary if you logged after `env-update` has been run.

**Comment by TheChymera** [comment]
@kiwifb ok, `source /etc/profile` did the trick. Any way to make portage run this after the installation?

**Comment by kiwifb** [comment]
No, but usually `gcc` and `gcc-config` I think display a message saying you should do it if you intend to use it from an existing shell, so you display a message with `einfo` in `pkg_postinst` of the ebuild.

**Comment by TheChymera** [comment]
sounds good:

```

```
pkg_postinst() {
	echo
	einfo "Please run the following commands if you"
	einfo "intend to use fsl from an existing shell:"
	echo "env-update && source /etc/porfile"
        echo
}

**Comment by kiwifb** [comment]
yes that.
