### ISSUE TITLE
openblas soname suffix

### ISSUE THREAD

**Issue by Kagami** [gentoo-science/sci#556]
Hi.

Could you please explain, what's the point of adding suffix to the soname of `openblas` dynamic libraries depending on use flags selected? E.g. `+openmp` make it looks like `libopenblas_openmp.so` Some applications (e.g. caffe) pass `-lopenblas` to the compiler and fail with error because of this.

(I know that you also provide pkg-config files for `blas`, but not all applications use them.)

**Comment by kiwifb** [comment]
Generally speaking we think it is undesirable to depend on a specific `{c}blas` is there any technical reason `caffe` needs `openblas` specifically? If not, it should be made to accept any `{c}blas` the user wants to use.

**Comment by Kagami** [comment]
I'm not sure, probably that's limitation of caffe build system. They allow to select [few variants](https://github.com/BVLC/caffe/blob/03a84bf/Makefile#L342-L377) of BLAS implementations and pass fixed `-l` flags to the linker.

**Comment by kiwifb** [comment]
I'll admit that I would rip that whole section except the last two lines. In the ebuild I would export `BLAS_INCLUDE` and `BLAS_LIBS` to the result of calls to `pkg-config` and finally I would use the `flag-o-matic` eclass to add the result to `LDFLAGS`. It might look like this
```
inherit flag-matic toolchain-funcs
...
DEPEND="virtual/cblas
virtual/pkgconfig"
...
src_compile(){
BLAS_INCLUDE=$($(tc-getPKG_CONFIG) cbas --cflags-only-I)
BLAS_LIBS=$($(tc-getPKG_CONFIG) cbas --libs-only-L)
append-ldflags $($(tc-getPKG_CONFIG) cbas --libs-only-l)
...
```
Or something like that.

**Comment by Kagami** [comment]
I encountered similar problem with `boost_python` (gentoo package provides `libboost_python-2.7` instead of `libboost_python`) and ended up with editing few lines in caffe's Makefile. So closing this since fix is trivial.
