### ISSUE TITLE
can't emerge sci-libs/atlas-3.11.38-r1

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo-science/sci#583]
Here all the info
https://gist.github.com/Alessandro-Barbieri/60cefacff79c2d7ddf6b

**Comment by jlec** [comment]
> gcc version 4.9.3 (Gentoo 4.9.3 p1.5, pie-0.6.4) 
/usr/bin/gcc -V 2>&1  >> bin/INSTALL_LOG/ERROR.LOG
gcc: error: unrecognized command line option ‘-V’
gcc: fatal error: no input files
compilation terminated.

This looks strange. Is your system in good shape?

**Comment by Alessandro-Barbieri** [comment]
I have installed atlas-3.10.2 from this overlay with no problems.
What can I do to test that error?

**Comment by rtlix** [comment]
me too, the same error, it's a new built system, these days is having a problem with installing sage, just update gsl to v2.1, sci-libs/lapack-reference-3.6.0-r1 can't build and it seems that blas is in absent( before install and mark ~amd64 to gsl blas cblas, eselect blas shows reference, now it shows nothing), so I'm now looking for a blas to install
sci-libs/atlas-3.11.38-r1 failed with the same error mentioned above, atlas-3.10.2 seems to be working

**Comment by kiwifb** [comment]
`atlas-3.10.2` from the overlay or the main tree? Have you followed the instructions of https://wiki.gentoo.org/wiki/User_talk:Houseofsuns to move from the main tree blas/lapack to the science overlay way of handling this?

**Comment by rtlix** [comment]
let me see, it's:
[ebuild   R   ~] sci-libs/atlas-3.10.2::science  USE="fortran lapack -doc -generic -static-libs -threads" 0 KiB
it's from science overlay. I have just followed the instruction in the link you gave, but there is no blas listed with eselect, and lapack-reference doesn't compile, though gsl-2.1 is installed, so I have to find another blas , then I try to install atlas, failed on 3.11.38-r1, after found this topic, I tried 3.10.2, it works indeed! though It should have taken me 3 hours, 21 minutes and 2 seconds to build, btw my cpu is i5 6300hq! But everything goes well now! eselect blas list now shows :
  [1]   atlas
  [2]   openblas-openmp
  [3]   reference *
and I'm able to install sage now!

**Comment by kiwifb** [comment]
You shouldn't mistake `blas` and `cblas`, `gsl` only provides `cblas` while `atlas` provides both (when useflag `fortran` is set). `lapack` needs `blas`.
I recommend setting the `threads` useflag for `atlas`, without it the library can exhibit brokenness in some circumstances.

**Comment by rtlix** [comment]
thank you! not have realized that, I just found some blogs about blas and began to know what is blas, cblas or lapack. for atlas,  I'll add threads useflag and build it again (thank you so much!).

I find another problem matplot-1.5.1 failed to compile:
```

  File "/usr/lib64/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
ImportError: cannot import name scimath
 * ERROR: dev-python/matplotlib-1.5.1::gentoo failed (compile phase):
 *   (no error message)

```
should I post another bug?

**Comment by Alessandro-Barbieri** [comment]
also in https://bugs.gentoo.org/show_bug.cgi?id=603324

**Comment by Alessandro-Barbieri** [comment]
LTO is too broken for me

**Comment by archenroot** [comment]
I was facing same issue unable to compile latest version. I have multiple GCC instances installed on my box:
```
ares ~ # gcc-config -l
 [1] x86_64-pc-linux-gnu-4.9.4
 [2] x86_64-pc-linux-gnu-5.4.0 *
 [3] x86_64-pc-linux-gnu-6.3.0
 [4] x86_64-pc-linux-gnu-7.1.0
```
I was trying to build with 7 then 6 and 5, all failures. Very interesting is that I am able to compile my own version in archenroot/gentoo-overlay which is atlas-3.10.3 :-) Not sure what is the reason here.

Regarding the -V option it is definitelly something wrong with detection of GCC version where multiple versions are supported. The -V was used as per my understanding on 4 and earlier version whereas -v is support from 5 onwards. So for some reason it looks like the make process doesn't detect the right one.

Still my 3.10.3 works.

**Comment by archenroot** [comment]
>>> Installing (1 of 1) sci-libs/atlas-3.10.3::archenroot

>>> Recording sci-libs/atlas::archenroot in "world" favorites file...

 * Messages for package sci-libs/atlas-3.10.3:

 * /var/lib/layman/archenroot/sci-libs/atlas/files/cpu-throttling-check-disabled.patch
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: config file '/etc/modprobe.d/bbswitch.conf' needs updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.

 * IMPORTANT: 22 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

ares atlas # eselect cblas list
Available providers for cblas:
  [1]   atlas *
  [2]   gsl

I will try again the latest in current shell again without any single change.

**Comment by Alessandro-Barbieri** [comment]
If you didn't used LTO I'll reopen this

**Comment by archenroot** [comment]
@Alessandro-Barbieri Sorry, I am not that skilled in compilation phases (while heavily learning), I understand what is link time optimization, but not sure what you refer to.

To summarize: there is ebuild in science overlay which is failing in the moment for Atlas. And I have one in my overlay which is not failing, but is different version. I didn't diff those 2 diffs about how they differ. If they don't differ it could be some issue with atlas itself. I had already issue with magma lib for instance which I had to fix upstream....

**Comment by Alessandro-Barbieri** [comment]
@archenroot if you didn't put `-flto` in your `CFLAGS` I'll reopen
