### ISSUE TITLE
Building OpenBLAS on amd64 for x86 fails

### ISSUE THREAD

**Issue by poboiko** [gentoo-science/sci#591]
I have and amd64 machine; when portage was trying to build OpenBLAS for x86 (multilib), it failed with following message:

> x86_64-pc-linux-gnu-ar: strmm_kernel_LN.o: No such file or directory

Lurking for the solution, I ran into an [upstream issue](https://github.com/xianyi/OpenBLAS/issues/657), which suggested to modify MAKEOPTS. So I modified ebuild to add BINARY=32 to MAKEOPTS when building for x86 architecture; and it fixed my problem.

Simple proposed patch for ebuild:
```
diff` --git a/sci-libs/openblas/openblas-0.2.15.ebuild b/sci-libs/openblas/openblas-0.2.15.ebuild
index 61fbdc5..3ecd37e 100644
--- a/sci-libs/openblas/openblas-0.2.15.ebuild
+++ b/sci-libs/openblas/openblas-0.2.15.ebuild
@@ -49,6 +49,9 @@ get_openblas_flags() {
 		local libnamesuffix="${underscoresuffix#_}"
 		openblas_flags+=( LIBNAMESUFFIX=${libnamesuffix} )
 	fi
+	if [[ "${ABI}" == "x86" ]]; then 
+		openblas_flags+=( BINARY=32 );
+	fi
 	echo "${openblas_flags[@]}"
 }
```

**Comment by jlec** [comment]
Thanks for the report, I will look into that.

**Comment by jlec** [comment]
Strangely it works for me here.
