### ISSUE TITLE
Compile MRIcron with lazarus-1.6.0

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#596]
Hi, I am trying to compile `sci-visualization/mricron` with the latest `lazarus` . It seems to fail with an access violation, as seen [in this log](https://bpaste.net/show/a533095d00ee). Any ideas why this happens or what we can do about it?

**Comment by jlec** [comment]
No idea, perhaps you should ask upstream.

**Comment by neurolabusc** [comment]
It looks like you are using
  Free Pascal Compiler version 2.6.4 [2015/10/16] for x86_64
For Lazarus 1.6 you will want FPC and FPC-soources 3.0.0. If you have problems after updating, try loading the graphical IDE (using "startlazarus" from the command line) and compiling some of the example projects. When the IDE launches it checks your configuration. If you have any problems with the example projects you can get help from the community (http://mantis.freepascal.org/).

**Comment by TheChymera** [comment]
The live MRIcron (at laeast [for now](https://github.com/neurolabusc/MRIcron/tree/8f7e87555df5ce2d2f9ce6f0fe0a8e8077a7a2b2)) compiles with `=dev-lang/lazarus-1.6.2`.
