### ISSUE TITLE
sci-libs/calculix-ccx-2.8_p2 source file unavailable (error 404)

### ISSUE THREAD

**Issue by apieum** [gentoo-science/sci#602]
Can't emerge calculix as the source file was removed.

```
>>> Emerging (1 of 1) sci-libs/calculix-ccx-2.8_p2::science
>>> Downloading 'http://distfiles.gentoo.org/distfiles/ccx_2.8p2.src.tar.bz2'
--2016-03-06 14:25:59--  http://distfiles.gentoo.org/distfiles/ccx_2.8p2.src.tar.bz2
Resolving distfiles.gentoo.org... 137.226.34.46, 156.56.247.195, 64.50.236.52, ...
Connecting to distfiles.gentoo.org|137.226.34.46|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-06 14:25:59 ERROR 404: Not Found.

>>> Downloading 'http://www.dhondt.de/ccx_2.8p2.src.tar.bz2'
--2016-03-06 14:25:59--  http://www.dhondt.de/ccx_2.8p2.src.tar.bz2
Resolving www.dhondt.de... 2a01:238:20a:202:1094::, 81.169.145.94
Connecting to www.dhondt.de|2a01:238:20a:202:1094::|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-06 14:26:00 ERROR 404: Not Found.

!!! Couldn't download 'ccx_2.8p2.src.tar.bz2'. Aborting.
```

**Comment by jlec** [comment]
it needs to be updated CC @TheChymera

**Comment by TheChymera** [comment]
Sorry, I know nothing about this package. What made you think otherwise?

A rapid search on google showed that a newer version is available for download here: http://www.dhondt.de/ccx_2.10.src.tar.bz2

Perhaps this is one of those packages where upstream takes the old sources down as soon as they release new ones?

I guess we should:
* version bump the package
* find the old sources and reposit them ourselves?

**Comment by apieum** [comment]
> Perhaps this is one of those packages where upstream takes the old sources down as soon as they release new ones?
Yes it is.
It is not the first and only one like that. I wonder if we can find a solution to host packages sources somewhere else to avoid these issues ?

I've reported it but don't worry if I find enough time I would submit a pr for the new version.

**Comment by TheChymera** [comment]
I agree - we need to find a better solution for such packages. I am getting the same with sci-biology/fsl every few months....

**Comment by apieum** [comment]
@TheChymera I've contacted the lib author to ask him if he can let old versions on his server, but the truth is I would not think to update the ebuild for new version if it didn't stop to work.

Is there any webcrawler that can scans all packages sources on gentoo repos and tell us for new versions ? (how are doing gentoo devs ? @jlec maybe you know ?)

**Comment by jlec** [comment]
@apieum the gentoo mirror system will transfer all source onto our mirrors from the primary source. But that doesn't work for overlays. I can host file in my devspace if needed

@TheChymera I thought you brought that package in. Sorry for the noise. I was @Fat-Zer .

**Comment by Fat-Zer** [comment]
yes, the upstream removes old tarballs with a new release. That's the reason I've version bumped the 2.8p2.
If you are interested in placing old tarballs on some mirror, I still have got them locally and may upload somewhere.

**Comment by jlec** [comment]
@Fat-Zer Could you provide this somewhere so I can download it?

**Comment by Fat-Zer** [comment]
ccx_2.8p2.src.tar.bz2 (898 kB): https://fatzer.blaucloud.de/index.php/s/hzk1MTtXWjoiTe5/download
ccx_2.8p2.ps.tar.bz2 (2.3 MB): https://fatzer.blaucloud.de/index.php/s/wpRre5lR7rFT8q2/download
ccx_2.8p2.test.tar.bz2 (8.6 MB): https://fatzer.blaucloud.de/index.php/s/VCWTfaUAOUm6nQI/download

**Comment by jlec** [comment]
They are now placed in

https://dev.gentoo.org/~jlec/distfiles/

**Comment by apieum** [comment]
The author aswered me and put back the old files on the server with the same url.
