### ISSUE TITLE
What do we do about $FSLDIR ?

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#610]
`sci-biology/fsl` has a variable called `$FSLDIR`. This is meant to inform FSL functions on where FSL is installed, and FSL functions inside FSL are (afaict) always called like `$FSLDIR/bin/FUNCTIONNAME`.

Apparently we set `FSLDIR=/usr` in `/etc/env.d/99fsl` - but I am thinking handling this a bit differently might help us better deal with issues such as executable name collisions (as suggested [here](https://github.com/gentoo-science/sci/issues/606) we could just change the name, but there are packages soutside of FSL proper which also need to know how to call these renamed functions - see a discussion about that [here](https://github.com/nipy/nipype/issues/1415)).

I am wondering whether it is reasonable to put stuff under `/usr/local/fsl` - and just add a few functions (for which we know there are no conflicts) under `/usr/bin`.

Any ideas on this, @kiwifb ?

**Comment by TheChymera** [comment]
Apparently NeuroDebian installs FSL bianries in `/usr/share/fsl/bin/` (and sets `$FSLDIR` to `/usr/share/fsl/`) - and then creates symlinks to these files in /usr/bin prepending `${P}_` to the name.

**Comment by TheChymera** [comment]
Is this what would do that in portage:

```
src_install() {
    for file in bin/*
    do
        dosym "${ED}"/usr/bin/"${P}"_file file
    done
}
?

**Comment by kiwifb** [comment]
I usually go for `/usr/lib{,64}/fsl/`. I don't think your procedure would work.

**Comment by TheChymera** [comment]
I don't understand what you mean - what do you do with `/usr/lib{,64}/fsl/` ? do you set FSLDIR to that? It seems to me our current installation is installing FSL files here `insinto /usr/share/${PN}`

What procedure exactly do you think would not work?

**Comment by kiwifb** [comment]
`/usr/share/${PN}` is fine, especially if we already do it. I am on a conference call at the same time but your `dosym` stuff looks wrong.

**Comment by TheChymera** [comment]
As of https://github.com/gentoo-science/sci/pull/716 we are addressing the issue of FSLDIR by:

* Setting it to `/usr/share/fsl`
* Placing whatever files belong there in there (currently `data/`)
* Placing all other files in the appropriate filesystem locations
* Adding symlinks under `/usr/share/fsl` to allow FSL and dependencies to find FSL files.
