### ISSUE TITLE
sci-mathematics/scilab: Broken deps

### ISSUE THREAD

**Issue by khumba** [gentoo-science/sci#627]
Hi,

With regard to 7cce2dc (Mask sci-mathematics/scilab due to broken dep tree), what is the missing dependency?  I can't tell because it still builds fine for me.  I'm interesting in getting this unmasked.  CC @jlec.

Thanks.

**Comment by marbre** [comment]
Reverting  7cce2dc  and executing `repoman full` one gets:

```
  dependency.bad [fatal]        52
   sci-mathematics/scilab/scilab-5.5.2-r1.ebuild: DEPEND: ~amd64(default/linux/amd64/13.0)
[     'dev-java/freehep-graphicsio',
      'dev-java/freehep-graphicsio-emf',
      'dev-java/freehep-graphics2d',
      'dev-java/freehep-io',
      'dev-java/freehep-util']
   sci-mathematics/scilab/scilab-5.5.2-r1.ebuild: RDEPEND: ~amd64(default/linux/amd64/13.0)
[     'dev-java/freehep-graphicsio',
      'dev-java/freehep-graphicsio-emf',
      'dev-java/freehep-graphics2d',
      'dev-java/freehep-io',
      'dev-java/freehep-util']

...
```

All `freehep` packages seem to be masked, thus also `scilab` needs to be masked.

**Comment by khumba** [comment]
Got it, thanks @marbre.  For starters, Scilab only depends on FreeHEP for EMF file export support.  Would it be alright to revert the package mask and simply package.use.mask `sci-mathematics/scilab emf` instead?  `repoman full` seems to be appeased by doing this, and I confirm I'm building it in this configuration already, without FreeHEP installed.  Should I open a pull request?

    CDEPEND="
            ...
            emf? (
                    dev-java/freehep-graphicsio
                    dev-java/freehep-graphicsio-emf
                    dev-java/freehep-graphics2d
                    dev-java/freehep-io
                    dev-java/freehep-util
            )
    "

**Comment by chewi** [comment]
We've decided to keep some of FreeHEP and the EMF package would only be one extra. I'll start on that now. freehep-util is going away but at least some of it seems to have moved into freehep-graphicsbase.

**Comment by chewi** [comment]
This is now in the tree.

**Comment by khumba** [comment]
That was quick, thanks!  `dev-java/freehep-util` is one of the bits Scilab needs and that's not in the tree, but since it's a dep only of Scilab, should it be added to this overlay instead?

**Comment by chewi** [comment]
freehep-util doesn't seem to be maintained upstream anymore, although even this newer stuff is starting to look a bit neglected. In the case of Sweet Home 3D, I just had to depend on freehep-graphicsbase instead and change one `import` line from `org.freehep.util.UserProperties` to `org.freehep.graphicsbase.util.UserProperties`. Hopefully you can do something similar.

**Comment by khumba** [comment]
Grepping for uses of `org.freehep.util` only turns up the configure script, and moreover FreeHEP usage is minimal:

    scilab-5.5.2 $ grep -rl org.freehep
    configure.ac
    configure
    modules/graphic_export/src/java/org/scilab/modules/graphic_export/convertToPPM/PPMEncoder.java
    modules/graphic_export/src/java/org/scilab/modules/graphic_export/Export.java
    scilab-5.5.2 $ grep -rn org.freehep configure.ac modules
    configure.ac:1007:                    AC_JAVA_CHECK_PACKAGE([freehep-graphics2d],[org.freehep.graphics2d.VectorGraphics],[Freehep Graphics2D])
    configure.ac:1012:                    AC_JAVA_CHECK_PACKAGE([freehep-graphicsio-emf],[org.freehep.graphicsio.emf.EMFGraphics2D],[Freehep GraphicsIO EMF])
    configure.ac:1017:                    AC_JAVA_CHECK_PACKAGE([freehep-graphicsio],[org.freehep.graphicsio.VectorGraphicsIO],[Freehep GraphicsIO])
    configure.ac:1022:                    AC_JAVA_CHECK_PACKAGE([freehep-io],[org.freehep.util.io.XMLSequence],[Freehep IO])
    configure.ac:1027:                    AC_JAVA_CHECK_PACKAGE([freehep-util],[org.freehep.util.StringUtilities],[Freehep Util])
    modules/graphic_export/src/java/org/scilab/modules/graphic_export/convertToPPM/PPMEncoder.java:43://import org.freehep.graphicsio.ImageEncoder;
    modules/graphic_export/src/java/org/scilab/modules/graphic_export/Export.java:1099:                g2dClass = (Class<Graphics2D>) Class.forName("org.freehep.graphicsio.emf.EMFGraphics2D");

However, when I try to patch the freehep-util dep out and export an EMF file, I get an exception and an empty file:

    Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/freehep/graphicsbase/util/UserProperties
            at java.lang.Class.forName0(Native Method)
            at java.lang.Class.forName(Class.java:264)
            at org.scilab.modules.graphic_export.Export$EMFExporter.<init>(Unknown Source)
            at org.scilab.modules.graphic_export.Export.getExporter(Unknown Source)
            at org.scilab.modules.graphic_export.Export.exportVectorial(Unknown Source)
            at org.scilab.modules.graphic_export.Export.exportVectorial(Unknown Source)
            at org.scilab.modules.graphic_export.Export.export(Unknown Source)
            at org.scilab.modules.graphic_export.FileExporter.fileExport(Unknown Source)
            at org.scilab.modules.graphic_export.FileExporter.fileExport(Unknown Source)
            at org.scilab.modules.gui.bridge.filechooser.ExportOptionWindow.actionPerformed(Unknown Source)
            <snip>
    Caused by: java.lang.ClassNotFoundException: org.freehep.graphicsbase.util.UserProperties
            at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            ... 106 more

Maybe this was a preexisting problem, I don't know.  But it seems to make sense to leave USE=emf masked versus patching something that isn't working anyway.  I'll clean up my PR.

**Comment by chewi** [comment]
There is no standard way of locating jars in java so you're generally left to the mercy of upstream launcher scripts that do all manner of weird things. In case this, it's probably relying on the paths picked up by configure so rather than removing freehep-util, you could replace it with freehep-graphicsbase. This is still potentially flaky though as it doesn't guard you against further changes to sub-dependencies that you would otherwise not need to care about.

We strongly advocate using Gentoo's Java infrastructure instead. If you don't want to install the jars manually using `java-pkg_dojar` then you can let Gentoo know about the jars installed by Autotools using `java-pkg_regjar`. Then replace the upstream launcher with one generated by `java-pkg_dolauncher`. I haven't seen Scilab's launcher so I don't know if there are additional things that it needs to take care of but they usually just need to locate Java, build a classpath, and fire up.

**Comment by khumba** [comment]
Thanks @thrasibule for fixing `USE=doc` and this error.  EMF output still doesn't work for me, but it's a different error now so I assume it's finding all its libs now.  Good to unmask Scilab now?

(Now I get a dialog saying "An error occurred during export: Unable to create export file, permission denied.")

**Comment by thrasibule** [comment]
I'm getting this error too... However the export still worked fine, it did create an emf file for me. Was it the case for you as well?

**Comment by khumba** [comment]
You're right.  pstoedit was crashing on the file, but LibreOffice was
able to open it fine, so Scilab's working.
