### ISSUE TITLE
Portage can't compile MRIcron 

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#633]
Recently, I tried to emerge the MRIcron ebuild again, and it no longer works. I can't pinpoint what upstream update “broke” the build, but I [contacted the author](https://github.com/neurolabusc/MRIcron/issues/3#issuecomment-225404154) and he suggested I compiled it by hand.

Turns out `lazbuild -B --lazarusdir="/usr/share/lazarus/" mricron.lpr` (run from the command line inside the cloned repo root dir) [works](https://bpaste.net/show/605d6256425f). While our ebuild [calling essentially the same code](https://github.com/gentoo-science/sci/blob/master/sci-visualization/mricron/mricron-9999.ebuild#L22) ends up [crashing](https://bpaste.net/show/f674e6d2985c).

Can you help me determine where the issue lies? The access violation for those language files from the crash log seems weird, and I have no idea why it is only triggered by portage.

**Comment by jlec** [comment]
you get an access violation in line [2023](https://bpaste.net/show/f674e6d2985c#2023). Make sure the build doesn't need to write in that dir or use ```addpredict``` to fake access.

**Comment by TheChymera** [comment]
ok, this is very weird:

```
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI="6"

inherit git-r3 gnome2-utils

DESCRIPTION="A simle medical imaging visualization tool"
HOMEPAGE="https://github.com/neurolabusc/MRIcron"
SRC_URI=""
EGIT_REPO_URI="https://github.com/neurolabusc/MRIcron.git"

LICENSE="BSD"
SLOT="0"

RDEPEND=""
DEPEND="dev-lang/fpc
	dev-lang/lazarus"

src_compile() {
	addpredict "/usr/share/lazarus/lcl/languages"
	lazbuild -B --lazarusdir="/usr/share/lazarus/" mricron.lpr || die "aaa"
}

src_install() {
	dobin mricron
	doicon icons/mricron.png
	make_desktop_entry mricron MRIcron mricron
}

pkg_postinst() {
	gnome2_icon_cache_update
}
pkg_postrm() {
	gnome2_icon_cache_update
}
```
the above works.


```
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI="6"

inherit git-r3 gnome2-utils

DESCRIPTION="A simle medical imaging visualization tool"
HOMEPAGE="https://github.com/neurolabusc/MRIcron"
SRC_URI=""
EGIT_REPO_URI="https://github.com/neurolabusc/MRIcron.git"

LICENSE="BSD"
SLOT="0"

RDEPEND=""
DEPEND="dev-lang/fpc
	dev-lang/lazarus"

src_compile() {
	addpredict "/usr/share/lazarus/lcl/languages"
	lazbuild -B --lazarusdir="/usr/share/lazarus/" mricron.lpr || die
}

src_install() {
	dobin mricron
	doicon icons/mricron.png
	make_desktop_entry mricron MRIcron mricron
}

pkg_postinst() {
	gnome2_icon_cache_update
}
pkg_postrm() {
	gnome2_icon_cache_update
}
```
But the above fails with [the aforementioned access violation error](https://bpaste.net/show/3d9593b43975). 
Another thing I don't entirely understand: if I emerge the program with the first ebuild (and do not unmerge it) I can successfully emerge it again with the second. @jlec can you help me figure out what the right fix is here?

**Comment by TheChymera** [comment]
the exact thing happens with MRIcroGL

**Comment by TheChymera** [comment]
In the mean time this has been fixed.
