### ISSUE TITLE
dev-util/VampirTrace fails with USE=-cuda

### ISSUE THREAD

**Issue by jlec** [gentoo-science/sci#66]
The ebuild inherits cuda even when USE=-cuda.

When there is a cuda-config in $PATH, that fails with:

>>> Preparing source in /var/tmp/portage/dev-util/VampirTrace-5.14.3/work/VampirTrace-5.14.3 ...
 * ERROR: dev-util/VampirTrace-5.14.3 failed (prepare phase):
 *   Could not determine supported gcc versions from cuda-config

When there is not, it fails with:

>>> Preparing source in /var/tmp/portage/dev-util/VampirTrace-5.14.3/work/VampirTrace-5.14.3 ...
/var/tmp/portage/dev-util/VampirTrace-5.14.3/temp/environment: line 636: cuda-config: command not found
 * Could not execute cuda-config
 * Make sure >=dev-util/nvidia-cuda-toolkit-4.2.9-r1 is installed
 * ERROR: dev-util/VampirTrace-5.14.3 failed (prepare phase):
 *   cuda-config not found

Given that the ebuild only depends on dev-util/nvidia-cuda-toolkit when USE=cuda, and cuda.eclass obviously requires dev-util/nvidia-cuda-toolkit,
the ebuild only should inheric cuda when USE=cuda.

(Or cuda.eclass should be fixed to be idenpotent when dev-util/nvidia-cuda-toolkit is not installed.)

**Comment by marbre** [comment]
I assume we can close this issue. I recently bumped to 5.14.4, which compiles without problems. If cuda is enabled `--with-cuda-dir=/opt/cuda` is passed during the configure phase.
