### ISSUE TITLE
dev-tex/pythontex-0.15 version bump

### ISSUE THREAD

**Issue by equaeghe** [gentoo-science/sci#705]
https://github.com/gpoore/pythontex/releases/tag/v0.15

Currently 0.14 is in the overlay.

**Comment by marbre** [comment]
@equaeghe Feel free to send a pull request. See [CONTRIBUTING.md](https://github.com/gentoo-science/sci/blob/master/CONTRIBUTING.md).

**Comment by equaeghe** [comment]
It seems like 0.15 requires fvextra, which is not in the current stable texlive (2014). I'll check whether it's in texlive 2015; I think it'll need 2016…

**Comment by equaeghe** [comment]
Version has been bumped apparently.
