### ISSUE TITLE
sys-cluster/modules-3.2.10-r1::science - ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'oscar-modules'

### ISSUE THREAD

**Issue by mmokrejs** [gentoo-science/sci#708]
Hi,
  after getting into my bash from Gentoo::RAP I get:

`ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'oscar-modules'`

  I can live with this but seems it is just because I emerged 

`[ebuild   R    ] sys-cluster/modules-3.2.10-r1::science  USE="X {-test}" 0 KiB`

  From hits in Google I infer it has probably something to do with e.g. oscar-modules/1.0.5 or lam-oscar-7.1.4 or modules-oscar-3.2.5-2 (whichever are current versions, the version numbers were in some Debian? report I googled out).

  I cannot find package of these in Gentoo so I will wait for some feedback first what packages to look for in my installation.

**Comment by kiwifb** [comment]
Just to be clear, you have some kind of `modules` already on the prefix host, and you have trouble once installing `modules` from the overlay?

**Comment by mmokrejs** [comment]
Actually right. Because from within the Gentoo::RAP-hosted bash I do not see the parent environment settings incl. "module" command available, I thought installing the modules inside Gentoo and maybe re-copying the settings is a posisble way. I haven't decided yet.

**Comment by mmokrejs** [comment]
Ah, you were very right!

```
$ cat ~/.bashrc 
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
$

$ tail /etc/bashrc
        fi
    done

    unset i
    unset pathmunge
fi
# vim:ts=4:sw=4
if test "$MODULE_OSCAR" = "" -a -f /etc/profile.d/00-modules.sh; then   # MODULES-3.2.10-Bull.3.1.el6.20140225-RPM-ADDITION
        . /etc/profile.d/00-modules.sh          # MODULES-3.2.10-Bull.3.1.el6.20140225-RPM-ADDITION
fi                                              # MODULES-3.2.10-Bull.3.1.el6.20140225-RPM-ADDITION
$
```

I will close this false issue, thank you for diagnosis.
