### ISSUE TITLE
sci-libs/mkl Broken files that requires: libcoi_device.so.0

### ISSUE THREAD

**Issue by lockie** [gentoo-science/sci#714]
Hello.
I've installed mkl, but now revdep-rebuild keeps rebuilding it:
```
 * Broken files that requires: libcoi_device.so.0 (64 bits)
	* /opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64_lin/libmkl_ao_worker.so
 * Assign files to packages
	* /opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64_lin/libmkl_ao_worker.so -> sci-libs/mkl-11.3.2.181
```

Tried with both -mic and mic USE flags.
How do I fix that?

**Comment by lockie** [comment]
NVM, solved by installing reference libraries.

**Comment by rtlix** [comment]
hello! do you mean lapack-reference? there is also something like blas-reference and blabla..

**Comment by lockie** [comment]
Hey!
Uhm I guess I've meant that I've installed the default libraries instead of mkl.

**Comment by rtlix** [comment]
do you mean you then use the default sci-libs/atlas instead of mkl? and the problem, the Broken files related to mkl, is not solved still?

**Comment by lockie** [comment]
> use the default sci-libs/atlas instead of mkl

Erm, I guess so.

>  the problem, the Broken files related to mkl, is not solved still?

Haven't tried actually.
