### ISSUE TITLE
can't emerge clblas missing CL-1.2 headers

### ISSUE THREAD

**Issue by fab128** [gentoo-science/sci#726]
Hello 
I get the following error when trying to emerge clblas:
ERROR: sci-libs/clblas-2.10::science failed (pretend phase):
 *   /usr/local/include/CL not found

There is also a message inviting me to do 'ln -s /usr/lib64/OpenCL/global/include/CL-1.2/ /usr/local/include/CL' to solve the issue... 
However, the /usr/lib64/OpenCL/global/include/CL-1.2/ directory is not present in my system, and I can't find whichever package is supposed to provide it. I'm running an AMD GPU and installed amdapp-3.0-r1.

I've also tried to link /usr/local/include/CL to /usr/lib64/OpenCL/global/include/CL/ directory which is present in my system. However emerge now fails in compile phase

**Comment by fab128** [comment]
[clblas-2.10build.log.gz](https://github.com/gentoo-science/sci/files/723696/clblas-2.10build.log.gz)

**Comment by mmokrejs** [comment]
I have the same issue here. 

I have virtual/cblas-3.6-r100 installed but not sci-libs/clblas-2.10::science

Let me say that the ewarn/einfo messages should respect ${EPREFIX} as well and print out the proper path.

**Comment by mmokrejs** [comment]
commit c6e174240bd956a16b04f89328e53630f066fc14
Author: Martin Mokrejš <mmokrejs@fold.natur.cuni.cz>
Date:   Thu Jan 26 20:40:35 2017 +0100

    sci-libs/clblas: apply previous fix also to the other ebuilds
    
    Package-Manager: Portage-2.3.3, Repoman-2.3.1

commit 615239e113d022a9298ed25b566fc4e74053c9a1
Author: Martin Mokrejš <mmokrejs@fold.natur.cuni.cz>
Date:   Thu Jan 26 20:38:23 2017 +0100

    sci-libs/clblas-2.10: fix broken symlink presence checks, github science issue #726
    
    This fixes broken check on EPREFIX-ed installations and IMHO clarifies that
    most people do not need to do the symlink magic if tehy installed eselect-cblas
    already.
    
    Package-Manager: Portage-2.3.3, Repoman-2.3.1

**Comment by fab128** [comment]
Thanks mmokrejs for the commit which removes the CL symbolic link bug, however emerge now still fails for me in compile phase (see previously attached build log).

**Comment by marbre** [comment]
@fab128 There are different OpenCL providers, and unfortunately these provide different OpenCL versions. It actually depends on which device you want to execute the OpenCL code. I actually don't have and AMD GPU, thus I don't have amdapp installed. OpenCL includes can be provided by mesa, intel-ocl-sdk, nvidia-cuda-toolkit and so on, but it is actually hard to track which OpenCL version is shipped. When writing this ebuild, OpenCL-1.2 was minimum, you should be able to use a more recent version (depending on what your device supports). 

@mmokrejs This issue has nothing to do with cblas, this OpenCL not C. Thus `eselect cblas`  is not involved at all!
Further, it is not a prefix issue in generall, but not any package ships the required OpenCL headers and eselect-opencl does not allow to choose which version is linked.

Excuse the late reply, currently only a limited time for Gentoo. Hope my reply clarifies this a little, however the ebuild was moved to the main tree by @sfabbro.

**Comment by mmokrejs** [comment]
@marbre Sorry for the noise then, I ran into an issue with /usr/lib64/OpenCL/global/include/CL-1.2/ not being symlinked properly from elsewhere and I thought it is provided by this package. You just explained that "OpenCL includes can be provided by mesa, ..." so now I understand am bit more. Well I think my changes were anyway good but actually I forgot to emphasize it was a non-maintainer commit. Sorry for that, I just forgot!

**Comment by marbre** [comment]
@mmokrejs No problem, just wanted to clarify. As I currently have only very limited time available, and especially if I read that my ebuilds are totally broken, I keep my answers short and they might not me as kind as they should be ;) Anyway, adding support for `${EPREFIX}` is a good thing, thanks.

@fab128 Can we close this issue?

**Comment by fab128** [comment]
According to its website, Amdapp SDK is OpenCL 2.0 compatible. So why Clblas shouldn't compile on my system ?

**Comment by marbre** [comment]
Because amdapp maybe isn't registered as provider in eselect-opencl or the wrong version of the includes is linked to /usr/include/CL.

**Comment by fab128** [comment]
I've manually linked /usr/include/CL to /opt/AMDAPP/include/CL and it now works. Thanks.
I've filled a new issue about amdapp package no doing this symbolic linking correctly on installation:
https://github.com/gentoo-science/sci/issues/729

I close this one.
