### ISSUE TITLE
missing license in license_groups

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo-science/sci#771]
Please add the CeCILL-B license to `profile/license_groups`
seems to be free (IANAL)

**Comment by kiwifb** [comment]
Do I have any ebuilds using that license? Otherwise it is quite enough for it to be merged in the science overlay.

**Comment by Alessandro-Barbieri** [comment]
Yes, sci-libs/givaro in both gentoo-science and sage-on-gentoo
